stages:
  - dump
  - push

variables:
  DOCKER_COMPOSE_PATH: "/apps/docker"

.dump-db:
  image: circleci/openjdk:11-browsers
  stage: dump
  services:
    - name: postgres:12.2-alpine
      alias: postgres
  before_script:
    - "which ssh-agent || ( apt update && apt install openssh-client -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PATRINAT_CI_SSH_KEY")
    - touch  ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-keyscan -v "$SERVER_URL" >> ~/.ssh/known_hosts
    - mkdir -p ~/biom-backup/postgresql/backup/
    - touch ~/biom-backup/postgresql/backup/backup.sql
    - (ssh -o stricthostkeychecking=no $PATRINAT_CI_USER@"$SERVER_URL" sudo docker exec -i diversity-postgres pg_dump --username biom --exclude-table-data=user) > ~/biom-backup/postgresql/backup/backup.sql
    - cat ~/biom-backup/postgresql/backup/backup.sql

dump-test-db:
  environment:
    name: test
    url: https://"$BIOM_TEST_SERVER_URL"
  variables:
    SERVER_URL: $BIOM_TEST_SERVER_URL
  extends: .dump-db

