stages:
  - dump

variables:
  DOCKER_COMPOSE_PATH: "/apps/docker"

.dump-db:
  image: circleci/openjdk:11-browsers
  stage: dump
  services:
    - name: postgres:12.2-alpine
      alias: postgres
  before_script:
    - "which ssh-agent || ( apt update && apt install openssh-client -y )"
    - eval $(ssh-agent -s)
    - git config --global user.email "gitlab-ci@mnhn.fr"
    - git config --global user.name "gitlab-ci"
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PATRINAT_CI_SSH_KEY")
    - touch  ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-keyscan -v "$SERVER_URL" >> ~/.ssh/known_hosts
    - cd ~
    - git clone git@ic-prod1.patnat.mnhn.fr:biom/biom-backup.git
    - cd biom-backup
    - git checkout $BRANCH_NAME
    - (ssh -o stricthostkeychecking=no $PATRINAT_CI_USER@"$SERVER_URL" sudo docker exec -i diversity-postgres pg_dump --username biom --exclude-table-data=user) > ~/biom-backup/postgresql/setup/01-backup.sql
    - rm -rf ~/biom-backup/diversity
    - scp -r $PATRINAT_CI_USER@"$SERVER_URL":/apps/diversity ~/biom-backup/
    - git add .
    - git commit -m "backup-$CI_JOB_ID"
    - git push

dump-test-db:
  only:
    refs:
      - schedules
    variables:
      - $ENV == "dev"
  environment:
    name: test
    url: https://"$BIOM_TEST_SERVER_URL"
  variables:
    SERVER_URL: $BIOM_TEST_SERVER_URL
    BRANCH_NAME: dev
  extends: .dump-db

dump-release-db:
  only:
    refs:
      - schedules
    variables:
      - $ENV == "release"
  environment:
    name: release
    url: https://"$BIOM_PREPROD_SERVER_URL"
  variables:
    SERVER_URL: $BIOM_PREPROD_SERVER_URL
    BRANCH_NAME: release
  extends: .dump-db
