version: '3.7'

services:

  db:
    image: postgres:13.1
    container_name: diversity-postgres
    environment:
      - POSTGRES_PASSWORD=DB_PWD
      - POSTGRES_USER=biom
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - 5432:5432
    restart: always
    volumes:
      - /apps/postgresql/setup:/docker-entrypoint-initdb.d
      - /apps/postgresql/data:/var/lib/postgresql/data
  diversity-app:
    image: outils-patrinat.mnhn.fr/biom-release:latest
    container_name: diversity-app
    environment:
     - "DIVERSITY_IMAGES_DIRECTORY=/srv/diversity"
     - "DIVERSITY_CONTACT_EMAIL=contact@biodiversite-outre-mer.fr"
     - "DIVERSITY_CONTACT_SUBJECT=[BIOM]"
     - "DIVERSITY_SECURITY_SECRET-KEY=8f6mLmz9XmFmmEaCAb+hzwCH91u4zUIQBbmqvvmZLPY="
     - "DIVERSITY_INDICATORS_BASE-URL=https://odata-indicateurs.mnhn.fr"
     - "DIVERSITY_IMPORT_BASE-URL=https://preprod.biodiversite-outre-mer.fr/"
     - "DIVERSITY_IMPORT_TOKEN=IMPORT_SOURCE_TOKEN"
     - "DIVERSITY_MATOMO_HOST=matomo.test.mnhn.fr"
     - "DIVERSITY_MATOMO_SITE-ID=7"
     - "SPRING_DATASOURCE_URL=jdbc:postgresql://biom-preprod.patnat.mnhn.fr/biom"
     - "SPRING_DATASOURCE_USERNAME=biom"
     - "SPRING_DATASOURCE_PASSWORD=beaN3xHl31d1mXhJSe30xmwmsFnnMpQv"
     - "SPRING_MAIL_HOST=smtp.mnhn.fr"
     - "SERVER_PORT=8080"
    ports:
      - 8080:8080
    volumes:
      - /apps/diversity/data:/srv/diversity
    restart: always
